// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miflbztkdctpibawermj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZmxienRrZGN0cGliYXdlcm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NTU3MTcsImV4cCI6MjA3NjAzMTcxN30.KE-lWqIEZR0T17Bd2HceLNM8HyTald0l_emlmHl7Va4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});