name: Deploy Snapshot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run snapshot
      - name: Include HTML report if present
        run: |
          if [ -d reports ]; then
            mkdir -p .snapshot/reports
            cp -R reports/* .snapshot/reports/
          fi
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .snapshot
      - id: deploy
        uses: actions/deploy-pages@v4
