name: Deploy Snapshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Use install (no lockfile in repo), then build the snapshot site
      - run: npm install
      - run: npm run snapshot

      # Ensure the site exists: .snapshot/index.html should be present
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .snapshot
      - uses: actions/deploy-pages@v4
